id: IA88AC974
ocr_import_info:
  timestamp: '2023-09-29T10:46:50.948987+00:00'
  batch_id: batch-f002
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 13:34:41.423005+00:00
last_modified: 2023-09-29 13:34:41.423012+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25132
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25132
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་ཀུན་ལས་བཏུས་པའི་རྒྱ་ཆེར་འགྲེལ་པ་ལེགས་པར་བཤད་པའི་རྒྱ་མཚོ།
  languages:
  - bo
  author: རེད་མདའ་བ་གཞོན་ནུ་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.9951546458508922
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG25140:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25140
      total_pages: 514
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG25140.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9950513422146562
  I1KG25139:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25139
      total_pages: 658
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG25139.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9952348653693686
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
